import type { Photo, ScheduledPin, Settings, BoardMapping, PhotoStats, QueueResponse } from './types';

export const mockPhotos: Photo[] = [
  {
    id: 'p1',
    drive_file_id: 'gd_001',
    file_name: 'bridal-henna-01.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_001',
    thumbnail_url: null,
    storage_url: null,
    status: 'new',
    tags: [],
    created_at: '2026-02-25T10:00:00Z',
    updated_at: '2026-02-25T10:00:00Z',
  },
  {
    id: 'p2',
    drive_file_id: 'gd_002',
    file_name: 'nail-art-gold.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_002',
    thumbnail_url: null,
    storage_url: null,
    status: 'new',
    tags: [],
    created_at: '2026-02-25T11:00:00Z',
    updated_at: '2026-02-25T11:00:00Z',
  },
  {
    id: 'p3',
    drive_file_id: 'gd_003',
    file_name: 'floral-centerpiece.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_003',
    thumbnail_url: null,
    storage_url: null,
    status: 'tagged',
    tags: ['floral', 'centerpiece', 'wedding', 'roses'],
    created_at: '2026-02-24T09:00:00Z',
    updated_at: '2026-02-25T14:00:00Z',
  },
  {
    id: 'p4',
    drive_file_id: 'gd_004',
    file_name: 'mehndi-traditional.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_004',
    thumbnail_url: null,
    storage_url: null,
    status: 'tagged',
    tags: ['mehndi', 'traditional', 'henna', 'bridal'],
    created_at: '2026-02-24T10:00:00Z',
    updated_at: '2026-02-25T15:00:00Z',
  },
  {
    id: 'p5',
    drive_file_id: 'gd_005',
    file_name: 'desi-outfit-red.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_005',
    thumbnail_url: null,
    storage_url: null,
    status: 'tagged',
    tags: ['desi', 'outfit', 'red', 'lehenga', 'wedding'],
    created_at: '2026-02-23T08:00:00Z',
    updated_at: '2026-02-24T12:00:00Z',
  },
  {
    id: 'p6',
    drive_file_id: 'gd_006',
    file_name: 'henna-hand-detail.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_006',
    thumbnail_url: null,
    storage_url: null,
    status: 'tagged',
    tags: ['henna', 'hand', 'detail', 'intricate'],
    created_at: '2026-02-23T09:00:00Z',
    updated_at: '2026-02-24T13:00:00Z',
  },
  {
    id: 'p7',
    drive_file_id: 'gd_007',
    file_name: 'bridal-makeup-look.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_007',
    thumbnail_url: null,
    storage_url: null,
    status: 'scheduled',
    tags: ['bridal', 'makeup', 'glam', 'wedding'],
    created_at: '2026-02-22T10:00:00Z',
    updated_at: '2026-02-24T16:00:00Z',
  },
  {
    id: 'p8',
    drive_file_id: 'gd_008',
    file_name: 'neutral-aesthetic-01.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_008',
    thumbnail_url: null,
    storage_url: null,
    status: 'scheduled',
    tags: ['neutral', 'aesthetic', 'minimalist'],
    created_at: '2026-02-22T11:00:00Z',
    updated_at: '2026-02-24T17:00:00Z',
  },
  {
    id: 'p9',
    drive_file_id: 'gd_009',
    file_name: 'nail-french-tip.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_009',
    thumbnail_url: null,
    storage_url: null,
    status: 'posted',
    tags: ['nails', 'french tip', 'elegant', 'manicure'],
    created_at: '2026-02-20T10:00:00Z',
    updated_at: '2026-02-23T10:00:00Z',
  },
  {
    id: 'p10',
    drive_file_id: 'gd_010',
    file_name: 'floral-bouquet-pastel.jpg',
    drive_url: 'https://drive.google.com/file/d/gd_010',
    thumbnail_url: null,
    storage_url: null,
    status: 'posted',
    tags: ['floral', 'bouquet', 'pastel', 'spring'],
    created_at: '2026-02-19T10:00:00Z',
    updated_at: '2026-02-22T10:00:00Z',
  },
];

export const mockScheduledPins: ScheduledPin[] = [
  {
    id: 'sp1',
    photo_id: 'p7',
    title: 'Stunning Bridal Makeup Inspiration',
    description: 'Get inspired by this gorgeous bridal glam look',
    board_id: 'b2',
    board_name: 'Bridal',
    link_url: 'https://example.com/bridal-makeup',
    position: 1,
    scheduled_for: '2026-03-01T10:00:00Z',
    posted_at: null,
    pinterest_pin_id: null,
    paused: false,
    photo: mockPhotos[6],
    tags: ['bridal', 'makeup', 'glam', 'wedding'],
  },
  {
    id: 'sp2',
    photo_id: 'p8',
    title: 'Minimalist Neutral Aesthetic',
    description: 'Clean and serene neutral tones for your boards',
    board_id: 'b8',
    board_name: 'Neutral',
    link_url: null,
    position: 2,
    scheduled_for: '2026-03-02T10:00:00Z',
    posted_at: null,
    pinterest_pin_id: null,
    paused: false,
    photo: mockPhotos[7],
    tags: ['neutral', 'aesthetic', 'minimalist'],
  },
  {
    id: 'sp3',
    photo_id: 'p3',
    title: 'Beautiful Floral Centerpiece Ideas',
    description: 'Perfect centerpiece for weddings and events',
    board_id: 'b4',
    board_name: 'Floral',
    link_url: 'https://example.com/floral-ideas',
    position: 3,
    scheduled_for: '2026-03-03T10:00:00Z',
    posted_at: null,
    pinterest_pin_id: null,
    paused: false,
    photo: mockPhotos[2],
    tags: ['floral', 'centerpiece', 'wedding', 'roses'],
  },
  {
    id: 'sp4',
    photo_id: 'p9',
    title: 'Elegant French Tip Nails',
    description: 'Classic french tip manicure inspiration',
    board_id: 'b3',
    board_name: 'Nails',
    link_url: 'https://example.com/nail-art',
    position: 4,
    scheduled_for: null,
    posted_at: '2026-02-23T10:00:00Z',
    pinterest_pin_id: 'pin_12345',
    paused: false,
    photo: mockPhotos[8],
    tags: ['nails', 'french tip', 'elegant', 'manicure'],
  },
  {
    id: 'sp5',
    photo_id: 'p10',
    title: 'Pastel Spring Bouquet',
    description: 'Lovely pastel flower arrangement for spring',
    board_id: 'b4',
    board_name: 'Floral',
    link_url: null,
    position: 5,
    scheduled_for: null,
    posted_at: '2026-02-22T10:00:00Z',
    pinterest_pin_id: 'pin_12346',
    paused: false,
    photo: mockPhotos[9],
    tags: ['floral', 'bouquet', 'pastel', 'spring'],
  },
];

export const mockSettings: Settings = {
  drive_folder_id: '1aBcDeFgHiJkLmNoPqRsT',
  posting_interval_hours: 24,
  default_post_time: '10:00',
  google_connected: true,
  pinterest_connected: true,
};

export const mockBoardMappings: BoardMapping[] = [
  { id: 'bm1', category: 'henna', board_id: 'b1', board_name: 'Henna Designs', link_url: 'https://example.com/henna' },
  { id: 'bm2', category: 'bridal', board_id: 'b2', board_name: 'Bridal Inspiration', link_url: 'https://example.com/bridal' },
  { id: 'bm3', category: 'nails', board_id: 'b3', board_name: 'Nail Art Ideas', link_url: 'https://example.com/nails' },
  { id: 'bm4', category: 'floral', board_id: 'b4', board_name: 'Floral Arrangements', link_url: 'https://example.com/floral' },
  { id: 'bm5', category: 'mehndi', board_id: 'b5', board_name: 'Mehndi Patterns', link_url: 'https://example.com/mehndi' },
  { id: 'bm6', category: 'desi', board_id: 'b6', board_name: 'Desi Fashion', link_url: 'https://example.com/desi' },
  { id: 'bm7', category: 'outfits', board_id: 'b7', board_name: 'Outfit Inspo', link_url: 'https://example.com/outfits' },
  { id: 'bm8', category: 'neutral', board_id: 'b8', board_name: 'Neutral Aesthetic', link_url: null },
];

export const mockPhotoStats: PhotoStats = {
  new: 2,
  tagged: 4,
  approved: 0,
  scheduled: 2,
  posted: 2,
  skipped: 0,
};

export const mockQueueResponse: QueueResponse = {
  pins: mockScheduledPins,
  next_post: '2026-03-01T10:00:00Z',
  is_paused: false,
};

export const BOARD_CATEGORIES = ['henna', 'bridal', 'nails', 'floral', 'mehndi', 'desi', 'outfits', 'neutral'] as const;

export const mockActivityFeed = [
  { id: 'a1', type: 'sync' as const, message: 'Synced 3 new photos from Google Drive', time: '2026-02-28T09:30:00Z' },
  { id: 'a2', type: 'approve' as const, message: 'Approved "bridal-makeup-look.jpg" for posting', time: '2026-02-28T09:15:00Z' },
  { id: 'a3', type: 'post' as const, message: 'Posted "nail-french-tip.jpg" to Nails board', time: '2026-02-28T08:00:00Z' },
  { id: 'a4', type: 'tag' as const, message: 'Generated tags for "mehndi-traditional.jpg"', time: '2026-02-27T16:00:00Z' },
  { id: 'a5', type: 'approve' as const, message: 'Approved "neutral-aesthetic-01.jpg" for posting', time: '2026-02-27T14:30:00Z' },
  { id: 'a6', type: 'sync' as const, message: 'Synced 5 new photos from Google Drive', time: '2026-02-27T10:00:00Z' },
  { id: 'a7', type: 'post' as const, message: 'Posted "floral-bouquet-pastel.jpg" to Floral board', time: '2026-02-26T10:00:00Z' },
  { id: 'a8', type: 'tag' as const, message: 'Generated tags for "desi-outfit-red.jpg"', time: '2026-02-26T09:00:00Z' },
];
